<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2019/3/31
 * Time: 18:22
 */
namespace app\api\controller;

use think\Controller;

class Common extends Controller {

    protected $appid;
    protected $appsecret;
    protected $share_data = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->appid = 'wx0bbcbca6c77b60e9';
        $this->appsecret = '64d3fabc6be138e6257df98dd64f54cb';

        $full_url = $_SERVER['REQUEST_SCHEME'] . '://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $this->share_data = [
            'title' => '展示商城',
            'desc' => '展示商城',
            'link' => $full_url,
            'imgUrl' => 'http://show.jianghairui.com/430.jpg'
        ];

        $cmd = request()->controller() . '/' . request()->action();

    }

}